import { AuthProvider } from "@/app/context/AuthContext";
import Providers from "./providers";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Empire Laboratory",
  description: "Generated by Empire-Lab Energy",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      className={`${poppins.variable} h-full antialiased`}
    >
      {/* On utilise min-h-screen et h-full pour garantir la flexibilité sur tous les écrans */}
      <body className="font-poppins h-full min-h-screen w-full bg-gray-50 text-gray-900">
        <Providers>
          <AuthProvider>
            {children}
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}